name: Print the value
 
# Controls when the workflow will run, in this case manually
on: workflow_dispatch

jobs:
  PrintTheRepoValue:
    name: Print the environment value from the repo
    runs-on: ubuntu-latest
    steps: 
    - run: echo "${{ vars.repovar }}"

  PrintTheTest1Value:
    name: Print the value from test1
    runs-on: ubuntu-latest
    environment: test1
    steps:
    - run: echo "${{ vars.envvar1 }}"

  PrintTheTest2Value: 
    name: Print the value from test2
    runs-on: ubuntu-latest
    environment: test2
    steps:
    - run: echo "${{ vars.envvar1 }}
   
    
