name: Print the value
 
# Controls when the workflow will run, in this case manually
on: workflow_dispatch

jobs:
  PrintTheRepoValue:
    name: Print the environment value from the repo
    runs-on: ubuntu-latest
    steps: 
    - run: echo "${{ vars.repovar }}"
