name: Print the value
 
# Controls when the workflow will run, in this case manually
on: workflow_dispatch

jobs:
  PrintTheValue:
    name: Print the environment value
    runs-on: ubuntu-latest
    steps: 
    - run: echo "${{ vars.repovar1 }}"
