name: Work with Secrets

# Controls when the workflow will run, in this case manually
on: workflow_dispatch

jobs:
  PrintTheRepoSecretValue:
    name: Print the secret value from the repo
    runs-on: ubuntu-latest
    environment: = test1
    env: 
      repo_secret: ${{ secrets.reposecret }}
      env_secret: ${{ secrets.envsecret1 }}
      
    steps: 
      - name: Display secret
        run: echo "${{ env.repo_secret }}"
      - name: Check secret
        if: contains('${{ env.envvar1 }}', 'b')
        run: echo "The secret matched"
      - name: Check if not the secret
        if: ${{ env.env_secret }} == "This value was set in test1"
        run: echo "The secret didn't match"

        

 

      
      
       
        
         
        
   

