name: Work with Secrets

# Controls when the workflow will run, in this case manually
on: workflow_dispatch

jobs:
  PrintTheRepoSecretValue:
    name: Print the secret value from the repo
    runs-on: ubuntu-latest
    env: 
      repo_secret: ${{ secrets.reposecret }}
    steps: 
      - name: Display secret
        run: echo "${{ env.repo_secret }}"
      - name: Check secret
        if: ${{ env.repo_secret }} == "This secret was set at the repo"
        run: echo "The secret matched"
      - name: Check if not the secret
        if: ${{ env.repo_secret }} != "This secret was set at the repo"
        run: echo "The secret didn't match"
        

 

      
      
       
        
         
        
   

