name: Work with Secrets

# Controls when the workflow will run, in this case manually
on: workflow_dispatch

jobs:
  PrintTheRepoSecretValue:
    name: Print the secret value from the repo
    runs-on: ubuntu-latest
    steps: 
      - name: Display secret
        env: 
         repo_secret: ${{ secrets.reposecret }}
        run: echo "${{ env.repo_secret }}"

  CheckTheRepoSecretValue:
    name: Check the value of the secret
    runs-on: ubuntu-latest
    steps:
      - name: Check value
        env: 
         repo_secret: ${{ secrets.reposecret }}
         
        
   

