name: Work with Secrets

# Controls when the workflow will run, in this case manually
on: workflow_dispatch

jobs:
  PrintTheRepoSecretValue:
    name: Print the secret value from the repo
    runs-on: ubuntu-latest
    environment: test1
    env: 
      ENV_SECRET: ${{ secrets.envsecret1 }}
      MESSAGE: This value was set in test1
      
      
    steps: 
      - name: Display secret
        run: echo "${{ secrets.reposecret }}"
      - name: Check secret
        if:  ${{ ENV_SECRET == env.MESSAGE }}
        run: echo "The secret matched"
      - name: Not the secret
        if: ${{ env.ENV_SECRET != env.MESSAGE }}
        run: echo "The secret didn't match"
   
        

 

      
      
       
        
         
        
   

