name: Work with Secrets

# Controls when the workflow will run, in this case manually
on: workflow_dispatch

jobs:
  PrintTheRepoSecretValue:
    name: Print the secret value from the repo
    runs-on: ubuntu-latest
    env: 
      repo_secret: ${{ secrets.reposecret }}
    steps: 
      - name: Display secret
        run: echo "${{ env.repo_secret }}"
 

      
      
       
        
         
        
   

