name: Work with Secrets

# Controls when the workflow will run, in this case manually
on: workflow_dispatch

jobs:
  PrintTheRepoSecretValue:
    name: Print the secret value from the repo
    runs-on: ubuntu-latest
    environment: test1
    env: 
      repo_secret: ${{ secrets.reposecret }}
      ENV_SECRET: ${{ secrets.envsecret1 }}
      MESSAGE: This value was set in test2
      
      
    steps: 
      - name: Display secret
        run: echo "${{ env.repo_secret }}"
      - name: Check secret
        if:  ${{ env.ENV_SECRET == env.MESSAGE }}
        run: echo "The secret matched"
      - name: Not the secret
        if: ${{ env.ENV_SECRET != env.MESSAGE }}
        run: echo "The secret didn't match
   
        

 

      
      
       
        
         
        
   

